use regex_generate::Generator;
use serde::Serialize;

use crate::core::error::{CliError, ErrorCode};
use crate::core::output::Out;

use super::GenerateArgs;

#[derive(Serialize)]
struct Out0 {
    generated: String,
}

pub fn run(args: GenerateArgs, out: &Out) -> Result<(), CliError> {
    let mut gen = Generator::new(&args.pattern, rand::thread_rng(), 10).map_err(|e| {
        CliError::new(
            ErrorCode::InvalidRegex,
            format!("cannot generate from pattern: {e}"),
        )
        .with_input(serde_json::json!({"pattern": args.pattern}))
        .with_hint("regex-generate does not support lookaround, backrefs, or anchors")
    })?;
    let mut buf = Vec::new();
    gen.generate(&mut buf).map_err(|e| {
        CliError::new(ErrorCode::Internal, format!("regex-generate failed: {e}"))
    })?;
    let generated = String::from_utf8(buf).map_err(|_| {
        CliError::new(ErrorCode::InvalidUtf8, "generated bytes are not UTF-8")
    })?;
    out.emit_value(&Out0 { generated })
}
